#config-version=FGT601E-7.4.9-FW-build2681-240101
config system global
    set hostname "FGT-EXEMPLE"
end
config vdom
edit root
    config firewall address
        edit "LAN_USERS"
            set subnet 192.168.10.0 255.255.255.0
        next
        edit "SRV_WEB"
            set subnet 10.0.0.10 255.255.255.255
        next
        edit "SRV_DB"
            set subnet 10.0.0.20 255.255.255.255
        next
        edit "MAJ_EDITEUR"
            set type fqdn
            set fqdn "update.exemple-editeur.com"
        next
    end
    config firewall addrgrp
        edit "SERVEURS_INTERNES"
            set member "SRV_WEB" "SRV_DB"
        next
    end
    config firewall service custom
        edit "APP_METIER"
            set tcp-portrange 8443
        next
    end
    config firewall service group
        edit "WEB"
            set member "HTTP" "HTTPS"
        next
    end
    config firewall policy
        edit 1
            set name "LAN_vers_Internet"
            set srcintf "port1"
            set dstintf "port2"
            set srcaddr "LAN_USERS"
            set dstaddr "all"
            set action accept
            set schedule "always"
            set service "WEB"
            set logtraffic all
            set nat enable
        next
        edit 2
            set name "Acces_serveurs_web"
            set srcintf "port1"
            set dstintf "port3"
            set srcaddr "LAN_USERS"
            set dstaddr "SERVEURS_INTERNES"
            set action accept
            set schedule "always"
            set service "APP_METIER"
            set logtraffic all
        next
        edit 3
            set srcintf "any"
            set dstintf "any"
            set srcaddr "all"
            set dstaddr "all"
            set action accept
            set schedule "always"
            set service "ALL"
            set logtraffic disable
            set comments "regle temporaire debug"
        next
        edit 4
            set name "Maj_editeur"
            set srcintf "port3"
            set dstintf "port2"
            set srcaddr "SRV_WEB"
            set dstaddr "MAJ_EDITEUR"
            set action accept
            set schedule "always"
            set service "HTTPS"
            set logtraffic all
            set nat enable
        next
        edit 5
            set name "Bloc_tout"
            set srcintf "any"
            set dstintf "any"
            set srcaddr "all"
            set dstaddr "all"
            set action deny
            set schedule "always"
            set service "ALL"
            set status disable
        next
    end
next
end
